apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

configMapGenerator:
  - name: airflow-dags
    namespace: airflow
    files:
      - orders_pipeline.py=dags/orders_pipeline.py

generatorOptions:
  disableNameSuffixHash: true