apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-secrets
  namespace: airflow
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: vault

  target:
    name: airflow-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-password: "{{ .admin_password }}"
        fernet-key: "{{ .fernet_key }}"
        api-secret-key: "{{ .api_secret_key }}"
        jwt-secret: "{{ .jwt_secret }}"

  dataFrom:
    - extract:
        key: apps/airflow
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-postgresql
  namespace: airflow
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: vault

  target:
    name: airflow-postgresql
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        postgres-password: "{{ .postgres_password }}"
        password: "{{ .postgres_password }}"
        replication-password: "{{ .postgres_password }}"

  dataFrom:
    - extract:
        key: apps/airflow
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-metadata
  namespace: airflow
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: vault

  target:
    name: airflow-metadata
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        connection: >-
          postgresql+psycopg2://airflow:{{ .postgres_password }}@airflow-postgresql.airflow.svc.cluster.local:5432/airflow?sslmode=disable

  dataFrom:
    - extract:
        key: apps/airflow