apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../helm/airflow
  - external-secrets.yaml
  - route.yaml

configMapGenerator:
  - name: airflow-values-aws
    namespace: airflow
    files:
      - values.yaml=values.yaml
    options:
      labels:
        reconcile.fluxcd.io/watch: Enabled

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: airflow
      namespace: airflow
    patch: |-
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: ConfigMap
          name: airflow-values-aws
          valuesKey: values.yaml
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: Secret
          name: airflow-secrets
          valuesKey: admin-password
          targetPath: createUserJob.defaultUser.password