apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway/gateway.yaml
  - gateway/hubble.yaml
  - gateway/airflow.yaml
  - gateway/vault.yaml
  - data/rbac.yaml
  - storage/rustfs.yaml
  - airflow