apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coroot-helm-values
  namespace: observability
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: vault

  target:
    name: coroot-helm-values
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .admin_password }}"

        values.yaml: |
          authBootstrapAdminPasswordSecret:
            name: coroot-helm-values
            key: password

  data:
    - secretKey: admin_password
      remoteRef:
        key: apps/coroot
        property: admin_password