apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../helm/aws-load-balancer-controller
  - ../../helm/external-dns
  - ../../helm/cert-manager
  - gateway.yaml
  - echo-route.yaml